tasks:
  - init: |
      pyenv local 3.11
      python3.11 -m pip install --upgrade pip
      python -m venv venv
      source venv/bin/activate
      pip3 install uvicorn
      pip3 install -r requirements.txt
  - command: |
      source venv/bin/activate
      uvicorn main:app --reload

ports:
  - port: 8000
    visibility: private
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python