image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip
      pip install uvicorn
      pip install -r requirements.txt
  - command: |
      uvicorn main:db_api --reload

ports:
  - port: 8000
    visibility: private
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
